---
app:
  is-debug: true
  jwt-token:
    ACCESS_TOKEN_PRIVATE_KEY: "access_private_key"
    ACCESS_TOKEN_EXPIRED_IN: 15m
    ACCESS_TOKEN_MAX_AGE: 1
    REFRESH_TOKEN_PRIVATE_KEY: "refresh_private_key"
    REFRESH_TOKEN_EXPIRED_IN: 43200m #30 day
    REFRESH_TOKEN_MAX_AGE: 60

http:
  ip: 0.0.0.0
  port: 8080
  cors:
    debug: true
    allowed-methods: ["GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE"]
    allowed-origins:
      - "http://localhost:3000"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options-passthrough: true
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

mail:
  ssl: true

postgresql:
  host: 0.0.0.0
  port: "5432"
  username: postgres
  password: develop12+
  database: xenforo